language: swift
xcode_workspace: Circle.xcworkspace
xcode_scheme: CircleTests
os: ios
osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2

notifications:
  slack:
    secure: EY1XLijG8IeSiUaUIIPsA2wsAMJCTpnWwz6KYc3YuZbrktWzVkgyQ9WvwXv4eEasB9x+Zbf0IicIAy+NHmLBQO0yyHxzNcM1W26t48OkmZ2GMoYYkdX2BIBXWHThT5+Mv997qZVCLdBWdmjeUsZ1jurdF5scy+Jyrgpno0LO7loSiyIdRQ8bA2DCrKAuS002vG24OTXGbUHv74T7Qjemv9ZyCt/depa1pXFNpzFUNEUY+JRlaTYa9pg3FWsFaY2ZOQLGKrIvHR+p9SriI0AlTFdF0kBj+r2Pf941bkWA5LVN0+L+GFThZr6vTHZainFB/w0oFfC2x2vAY3Nc8a91QK8b0JGaVtCGeuNVAAqjKumiU5ZEepjBan4E+E0C125+cBFTexANB9iW/f5XkEX4vaopWeNirQHGJTa3k8q1dgJu8rU/0Hr0J62M8tl6vyZDpbKLm+pQBsLPRsdTvspGaIQPTdB07Cg2q73IgGrp+p4Dratqs6yRpL/ePw0FAP7rWFbHdnrJx7RvlzYKHLWIq3vLH32mLAhAkj8+PlLqtsrNo9I7RKvb0iQGvoczQvCaacYnOOSQJEFTII6R2feE5FVzxNpTf49g4OBCda7huaLW2sfFeL/uuzCkpCIyjcv4rUgM5I2L2/kOlJG1qaeYwO3Ot1/WXPHNmQavUoGgwas=
