language: swift
osx_image: xcode9.2
xcode_workspace: Circle.xcworkspace
xcode_scheme: Circle
cache: cocoapods
gemfile: Gemfile

before_install:
  #- travis_wait pod install --repo-update --silent
  - bundle install

script: 
 #- xcrun xcodebuild test -workspace Circle.xcworkspace -scheme Circle -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2'
  - ./fastlane/travis.sh

notifications:
  slack:
    secure: UFNaDYqXGIENwtONB+UCBl1zdivFI+lruuNSqRzThoieiWGoG4PJOqqA6IeHWEuosXd/1YzqAPQPXd/8YKL9t/KfsBmoBjYkM9L7eNpaH9+q1NxbKar+trknvYma1qyXlcOC8P6a9771ScAbWRbQIJPagQYK8v0ebBTcdlz3Lpw+CMpum9SOPuI68zP71Br08PMdyuyC/nLfOMwWB270mWr4D2KvMcQ5Hz1HgH1SkATmFXsszoFhV0xD+JeGSNzr9YG8A+iBLTexXRoV/TLhahy0ljYkqIDaQRGsR/kRxZmvbPyCO3d6bDnuNmKz2ds7QyUoYAm99KQ82XZwRvdIq5dAq6ErFvMH3nnMIKJ/mYbJAd0IFLZJaWeWzjo+LgcgIWdl7uBftBFhyxfmq3wDfajDGf/nEtOOpHw0oWNfFKbcFtPN2JQbUzhEfyKmu2iMW6BYNuv6ChrwDZC2v9PwjNmFN4vV6Ebd1TwkO02v0UFFzmlJpnAqTX2frmzjXd72pDFYZCR8HVvkPlaDiuhhRJfBD6ZmnitW5HlS8txrXiY07bZqodhTh8OMx3D7WYBjCmAY3683+HrT1J+JmBfOnpugad9ghLFjHwb4fM3vt852LsbbuVD+i65AAioJT6qL7Hlp7CZcfMZda7m7lB+aHjbJjgckjcipTxGWSldxkes=
