language: swift

before_install:
  - brew update
  - brew upgrade xctool
  - gem install bundler
  - bundle install

script: 
  - xcodebuild -workspace Circle.xcworkspace -list -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' -sdk iphonesimulator

stages:
  - unit_tests
  - test_flight

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

unit_tests:
  dependencies: []
  stage: unit_tests
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - fastlane test
  tags:
    - ios

os: ios
osx_image: xcode9.2

notifications:
  slack:
    secure: UFNaDYqXGIENwtONB+UCBl1zdivFI+lruuNSqRzThoieiWGoG4PJOqqA6IeHWEuosXd/1YzqAPQPXd/8YKL9t/KfsBmoBjYkM9L7eNpaH9+q1NxbKar+trknvYma1qyXlcOC8P6a9771ScAbWRbQIJPagQYK8v0ebBTcdlz3Lpw+CMpum9SOPuI68zP71Br08PMdyuyC/nLfOMwWB270mWr4D2KvMcQ5Hz1HgH1SkATmFXsszoFhV0xD+JeGSNzr9YG8A+iBLTexXRoV/TLhahy0ljYkqIDaQRGsR/kRxZmvbPyCO3d6bDnuNmKz2ds7QyUoYAm99KQ82XZwRvdIq5dAq6ErFvMH3nnMIKJ/mYbJAd0IFLZJaWeWzjo+LgcgIWdl7uBftBFhyxfmq3wDfajDGf/nEtOOpHw0oWNfFKbcFtPN2JQbUzhEfyKmu2iMW6BYNuv6ChrwDZC2v9PwjNmFN4vV6Ebd1TwkO02v0UFFzmlJpnAqTX2frmzjXd72pDFYZCR8HVvkPlaDiuhhRJfBD6ZmnitW5HlS8txrXiY07bZqodhTh8OMx3D7WYBjCmAY3683+HrT1J+JmBfOnpugad9ghLFjHwb4fM3vt852LsbbuVD+i65AAioJT6qL7Hlp7CZcfMZda7m7lB+aHjbJjgckjcipTxGWSldxkes=
