default_platform(:ios)

platform :ios do
 
  before_all do
  	clear_derived_data
    clean_build_artifacts
  end

  lane :test do
    scan(workspace: "Circle.xcworkspace",
         device: "iPhone 8 (11.2)",
         scheme: "Circle",
         skip_build: true,
         clean: true)
  end

  lane :beta do
    ensure_git_status_clean
  	increment_build_number(build_number: number_of_commits,
    					   xcodeproj: "Circle.xcodeproj")

  	#test
    match(type: "appstore",
    	  team_id: "P44LMMDHV3")
    build_app(scheme: "Circle",
           	  workspace: "Circle.xcworkspace",
              include_bitcode: false)

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

end
