update_fastlane
default_platform(:ios)

platform :ios do
 
  before_all do
  	cocoapods
  end

  lane :test do
    scan(workspace: "Circle.xcworkspace",
           devices: "iPhone 8 (11.2)",
            scheme: "Circle",
            clean: true,
            skip_build: true)
  end

end
