update_fastlane
default_platform(:ios)

platform :ios do
 
  before_all do
  	clear_derived_data
    clean_build_artifacts
    cocoapods
  end

  lane :test do
  	swiftlint(mode: :lint,
  			  strict: false,
			  ignore_exit_status: false)

    scan(workspace: "Circle.xcworkspace",
            device: "iPhone 8 (11.2)",
            scheme: "Circle",
            clean: true)
  end

end
